require_relative '../node_modules/react-native/scripts/react_native_pods'

# Disable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'AirplayDemo' do
  use_react_native!(
    :path => '../node_modules/react-native'
  )
  
  # Manually add react-native-video
  pod 'react-native-video', :path => '../node_modules/react-native-video'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
